apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config 
      volumes:
        - name: config-volume
          configMap:
            name: env-vars
